# Generated by Django 2.2 on 2020-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://pbs.twimg.com/profile_images/630563733656350720/tDOhLnsW_400x400.jpg', max_length=500),
        ),
    ]
