# Generated by Django 2.2 on 2020-09-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobbies_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://images.idgesg.net/images/article/2018/09/macos-high-sierra-folder-icon-100773103-large.jpg', max_length=500),
        ),
    ]
